version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "WJerryZ"
    commit-message:
      prefix: "Submodule Updates"
    reviewers:
      - "WJerryZ"
